In [41]:
# importação de bibliotecas

import pandas as pd                                             # importação de biblioteca para manipulação de dados
import numpy as np                                              # importação de biblioteca para manipulação de numeros
import seaborn as sns                                           # importação de biblioteca para visualização de dados graficamente
import plotly.express as px                                     # importação de biblioteca para visualização de dados graficamente
from sklearn.neural_network import MLPRegressor                 # importação de biblioteca para regressão com redes neurais
from sklearn.preprocessing import StandardScaler                # importação de biblioteca sklearn para normalização de dados
from sklearn.metrics import mean_squared_error                  # importação de biblioteca sklearn para calculo de erro

In [42]:
# carregamento de dados

plano_saude = pd.read_csv('./data/plano_saude2.csv')

In [43]:
# exploração da base de dados visualizando os registros

plano_saude

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [44]:
# separação de dados

X_plano_saude = plano_saude.values[ :, 0:1]
y_plano_saude = plano_saude.values[ :, 1]

In [45]:
# visualização das bases de dados

X_plano_saude

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [46]:
# visualização das bases de dados

y_plano_saude

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [47]:
# criando um range entre o valor minimo e o maximo da base de treino
# 18 - 63 anos

X_teste_arvore = np.arange(min(X_plano_saude), max(X_plano_saude), 0.1)
X_teste_arvore

array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [48]:
# tamanho da amostra

X_teste_arvore.shape

(450,)

In [49]:
# criando uma base de dados com os valores do range
# transformando a base de dados em uma matriz

X_teste_arvore = X_teste_arvore.reshape(-1, 1)
X_teste_arvore

array([[18. ],
       [18.1],
       [18.2],
       [18.3],
       [18.4],
       [18.5],
       [18.6],
       [18.7],
       [18.8],
       [18.9],
       [19. ],
       [19.1],
       [19.2],
       [19.3],
       [19.4],
       [19.5],
       [19.6],
       [19.7],
       [19.8],
       [19.9],
       [20. ],
       [20.1],
       [20.2],
       [20.3],
       [20.4],
       [20.5],
       [20.6],
       [20.7],
       [20.8],
       [20.9],
       [21. ],
       [21.1],
       [21.2],
       [21.3],
       [21.4],
       [21.5],
       [21.6],
       [21.7],
       [21.8],
       [21.9],
       [22. ],
       [22.1],
       [22.2],
       [22.3],
       [22.4],
       [22.5],
       [22.6],
       [22.7],
       [22.8],
       [22.9],
       [23. ],
       [23.1],
       [23.2],
       [23.3],
       [23.4],
       [23.5],
       [23.6],
       [23.7],
       [23.8],
       [23.9],
       [24. ],
       [24.1],
       [24.2],
       [24.3],
       [24.4],
       [24.5],
       [24

In [50]:
# implementação de redes neurais

In [51]:
# normalização dos dados

scaler_x = StandardScaler()
X_plano_scaled = scaler_x.fit_transform(X_plano_saude.reshape(-1, 1))

scaler_y = StandardScaler()
y_plano_scaled = scaler_y.fit_transform(y_plano_saude.reshape(-1, 1))

In [52]:
X_plano_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [53]:
y_plano_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [54]:
# criando um modelo de regressão e treinando

regressor_nn = MLPRegressor(max_iter=1000)
regressor_nn.fit(X_plano_scaled, y_plano_scaled.ravel())

MLPRegressor(max_iter=1000)

In [55]:
# score do modelo

regressor_nn.score(X_plano_scaled, y_plano_scaled.ravel())

0.9523844122752979

In [56]:
# grafico de dispersão com o treinamento do kernel = 'rbf' e dados normalizados

grafico = px.scatter(x = X_plano_scaled.ravel(), y = y_plano_scaled.ravel())
grafico.add_scatter(x = X_plano_scaled.ravel(), y = regressor_nn.predict(X_plano_scaled), name = 'Previsões')
grafico.show()

In [57]:
# erro medio quadratico

mean_error = scaler_y.inverse_transform(mean_squared_error(y_plano_scaled, regressor_nn.predict(X_plano_scaled)).reshape(-1, 1))
mean_error

array([[2681.4651862]])

In [58]:
# novo valor para o plano de saude
novo = [[40]]
novo = scaler_x.transform(novo)

In [59]:
# previsão do algoritmo

regressor_nn.predict(novo)

array([-0.52622144])

In [60]:
# previsão do algoritmo

novo = scaler_y.inverse_transform(regressor_nn.predict(novo).reshape(-1, 1))
novo

array([[1036.86137709]])