In [20]:
# importações necessarias para os testes

import pickle as pkl         # para salvar e carregar os arquivos
import numpy as np           # para trabalhar com numeros

In [21]:
# carregando os classificadores

NN = pkl.load(open('./data/classificador_NN.sav','rb'))
AD = pkl.load(open('./data/classificador_AD.sav', 'rb'))
SVM = pkl.load(open('./data/classificador_SVM.sav', 'rb'))

In [22]:
# carregando a base de dados

with open('./data/credit.pkl', 'rb') as f:
    X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pkl.load(f)

In [23]:
# concatenando as bases de dados
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste))
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste))

In [34]:
# teste com um registro da bas de dados

novo_registro = X_credit[0]
novo_registro

array([-1.3754462 ,  0.50630999,  0.10980934])

In [35]:
# processamento do registro para o classificador

novo_registro = novo_registro.reshape(1, -1)

In [36]:
# classes = [0(vai pagar o emprestimo), 1(não vai pagar o emprestimo)])] 

In [37]:
# teste com o classificador de redes neurais

NN.predict(novo_registro)  

array([0], dtype=int64)

In [38]:
# teste com o classificador SVM

SVM.predict(novo_registro)

array([0], dtype=int64)

In [39]:
# testes com o classificador Arvores de Decisão (AD)

AD.predict(novo_registro)

array([0], dtype=int64)

In [40]:
# consultando a probabilidade e confiança do classificador rede neural em um registro

proba_NN = NN.predict_proba(novo_registro)
confiança_NN = proba_NN.max()
confiança_NN

0.9999999999999998

In [41]:
# consultando a probabilidade e confiança do classificador arvore de decisão em um registro

proba_AD = AD.predict_proba(novo_registro)
confiança_AD = proba_AD.max()
confiança_AD

1.0

In [42]:
# consultando a probabilidade e confiança do classificador SVM em um registro
# necessário que o classificador SVM tenha sido treinado com o parametro 'probability' = True

proba_SVM = SVM.predict_proba(novo_registro)
confiança_SVM = proba_SVM.max()
confiança_SVM

0.9999978030910001

In [43]:
# combinação de classsificadores

classe_0 = 0
classe_1 = 0
confiança_min = 0.999999                        # confiança mínima deve ser definida dependendo do classificador
algoritmos = 0

if confiança_NN >= confiança_min:
    algoritmos += 1
    if NN.predict(novo_registro) == 1:
        classe_1 += 1
    else:
        classe_0 += 1

if confiança_AD >= confiança_min:
    algoritmos += 1
    if AD.predict(novo_registro) == 1:
        classe_1 += 1
    else:
        classe_0 += 1

if confiança_SVM >= confiança_min:
    algoritmos += 1
    if SVM.predict(novo_registro) == 1:
        classe_1 += 1
    else:
        classe_0 += 1

if classe_0 > classe_1:
    print(f'Cliente vai pagar o empréstimo, baseado em {algoritmos} algoritmos.')
else:
    print(f'Cliente não vai pagar o empréstimo, baseado em {algoritmos} algoritmos.')

Cliente vai pagar o empréstimo, baseado em 2 algoritmos.
