In [3]:
# importações necessarias para os testes

import pickle as pkl         # para salvar e carregar os arquivos
import numpy as np           # para trabalhar com numeros

In [4]:
# carregando os classificadores

NN = pkl.load(open('./data/classificador_NN.sav','rb'))
AD = pkl.load(open('./data/classificador_AD.sav', 'rb'))
SVM = pkl.load(open('./data/classificador_SVM.sav', 'rb'))

In [5]:
# carregando a base de dados

with open('./data/credit.pkl', 'rb') as f:
    X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pkl.load(f)

In [6]:
# concatenando as bases de dados
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste))
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste))

In [9]:
# teste com um registro da bas de dados

novo_registro = X_credit[0]
novo_registro

array([-1.3754462 ,  0.50630999,  0.10980934])

In [10]:
# processamento do registro para o classificador

novo_registro = novo_registro.reshape(1, -1)

In [ ]:
# classes = [0(vai pagar o emprestimo), 1(não vai pagar o emprestimo)])] 

In [11]:
# teste com o classificador de redes neurais

NN.predict(novo_registro)  

array([0], dtype=int64)

In [12]:
# teste com o classificador SVM

SVM.predict(novo_registro)

array([0], dtype=int64)

In [13]:
# testes com o classificador Arvores de Decisão (AD)

AD.predict(novo_registro)

array([0], dtype=int64)