In [2]:
# importações necessarias para os testes

import pickle as pkl         # para salvar e carregar os arquivos
import numpy as np           # para trabalhar com numeros

In [3]:
# carregando os classificadores

NN = pkl.load(open('./data/classificador_NN.sav','rb'))
AD = pkl.load(open('./data/classificador_AD.sav', 'rb'))
SVM = pkl.load(open('./data/classificador_SVM.sav', 'rb'))

In [4]:
# carregando a base de dados

with open('./data/credit.pkl', 'rb') as f:
    X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pkl.load(f)

In [5]:
# concatenando as bases de dados
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste))
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste))

In [13]:
# teste com um registro da bas de dados

novo_registro = X_credit[1999]
novo_registro

array([-1.03572293, -0.93978209,  0.04244312])

In [14]:
# processamento do registro para o classificador

novo_registro = novo_registro.reshape(1, -1)

In [15]:
# classes = [0(vai pagar o emprestimo), 1(não vai pagar o emprestimo)])] 

In [16]:
# teste com o classificador de redes neurais

NN.predict(novo_registro)  

array([1], dtype=int64)

In [17]:
# teste com o classificador SVM

SVM.predict(novo_registro)

array([1], dtype=int64)

In [18]:
# testes com o classificador Arvores de Decisão (AD)

AD.predict(novo_registro)

array([1], dtype=int64)

In [19]:
# combinação de classsificadores

classe_0 = 0
classe_1 = 0

if NN.predict(novo_registro) == 1:
    classe_1 += 1
else:
    classe_0 += 1

if AD.predict(novo_registro) == 1:
    classe_1 += 1
else:
    classe_0 += 1

if SVM.predict(novo_registro) == 1:
    classe_1 += 1
else:
    classe_0 += 1

if classe_0 > classe_1:
    print('Cliente vai pagar o empréstimo')
else:
    print('Cliente não vai pagar o empréstimo')

Cliente não vai pagar o empréstimo
