In [1]:
# importando as bibliotecas necessarias

import plotly.express as px                             # visualização de graficos
import plotly.graph_objects as go                       # visualização de graficos
import numpy as np                                      # calculos matematicos
from sklearn.preprocessing import StandardScaler        # padronização dos dados
import matplotlib.pylab as plt                          # biblioteca graficos
from scipy.cluster.hierarchy import dendrogram, linkage # biblioteca para fazer o dendograma
from sklearn.cluster import DBSCAN                      # algoritmo agrumaneto BDSCAN

In [2]:
# criando um dataset para uso de algrupamento hierarquico

base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

# visualização após a transformação 
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [3]:
# padronização dos dados

scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

# visualização após a padronização
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [8]:
# Criando algortimo

dbscan_salario = DBSCAN(eps=0.95, min_samples=2,)
dbscan_salario.fit(base_salario)

DBSCAN(eps=0.95, min_samples=2)

In [9]:
# visualização dos rotulos

rotulos = dbscan_salario.labels_
rotulos

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64)

In [10]:
# visualização grafica

grafico = px.scatter(x= base_salario[:, 0], y= base_salario[:, 1], color=rotulos)
grafico.show()