In [11]:
# importando as bibliotecas necessarias

import plotly.express as px                       # visualização de graficos
import plotly.graph_objects as go                 # visualização de graficos
import numpy as np                                # calculos matematicos
from sklearn.preprocessing import StandardScaler  # padronização dos dados
from sklearn.cluster import KMeans                # algortimo de agruoamento K-means
from sklearn.datasets import make_blobs           # geração de dados aleatórios

In [12]:
# trabalhando com dados randomicos

In [17]:
# gerando valores randomicos 

X_random, y_random = make_blobs(n_samples=300, 
                                centers=5, 
                                random_state=1)

In [18]:
# visualizando dados randomicos (X_random)

X_random

array([[-4.13696771e+00, -3.87431946e+00],
       [-3.46346333e+00,  8.58102499e-01],
       [-7.05152951e+00, -8.84792170e+00],
       [-1.92744799e+00,  4.93684534e+00],
       [-1.11168279e+01, -1.99726964e+00],
       [-8.20576492e-01,  5.33759195e+00],
       [-3.10367371e+00,  3.90202401e+00],
       [-8.37006175e+00, -3.61533685e+00],
       [-6.75016865e+00, -2.61117528e+00],
       [-3.01671262e+00,  2.58189128e-01],
       [-1.53773863e+00,  5.53597378e+00],
       [-2.34049658e+00,  2.00529027e+00],
       [-1.25606826e+00,  5.00006839e+00],
       [-1.92239914e+00,  1.28984016e+00],
       [-6.25763105e+00, -3.51792774e+00],
       [-6.90013777e+00, -3.68262853e+00],
       [-1.09811127e+00,  1.48938373e+00],
       [-1.38064919e+00,  4.22924697e-01],
       [-9.31764266e+00, -4.27315015e+00],
       [-5.06633944e+00, -1.97308366e+00],
       [-6.64960046e+00, -3.83875508e+00],
       [-1.88188805e+00,  4.20573180e+00],
       [-6.44379948e+00, -7.19710640e+00],
       [-1.

In [19]:
# visualizando dados gerados (y_random)

y_random

array([3, 4, 2, 0, 1, 0, 0, 1, 3, 4, 0, 4, 0, 4, 3, 3, 4, 4, 1, 3, 3, 0,
       2, 0, 0, 3, 1, 3, 1, 4, 1, 4, 3, 0, 0, 4, 3, 3, 1, 1, 3, 2, 2, 2,
       0, 2, 3, 0, 4, 1, 1, 0, 2, 2, 1, 0, 4, 4, 1, 2, 3, 2, 1, 2, 1, 3,
       0, 3, 0, 0, 4, 1, 1, 3, 2, 0, 0, 0, 2, 1, 2, 1, 0, 3, 1, 1, 2, 1,
       0, 3, 1, 3, 2, 3, 2, 2, 1, 2, 3, 1, 4, 4, 4, 4, 3, 3, 2, 2, 1, 3,
       3, 2, 1, 4, 3, 1, 0, 4, 2, 4, 1, 4, 3, 3, 0, 2, 0, 2, 2, 3, 1, 2,
       0, 4, 1, 3, 3, 1, 3, 2, 1, 1, 3, 3, 3, 4, 2, 3, 2, 1, 1, 4, 2, 2,
       4, 0, 3, 4, 1, 3, 1, 4, 1, 0, 2, 4, 2, 3, 2, 2, 0, 1, 4, 1, 2, 2,
       0, 0, 3, 1, 2, 2, 0, 1, 0, 3, 3, 4, 4, 0, 1, 0, 2, 0, 0, 1, 4, 2,
       4, 2, 0, 1, 0, 0, 3, 0, 1, 0, 1, 4, 4, 2, 3, 4, 1, 4, 4, 3, 2, 0,
       3, 0, 0, 4, 0, 4, 2, 1, 0, 1, 4, 2, 0, 4, 0, 2, 0, 0, 4, 1, 2, 4,
       4, 0, 3, 2, 4, 4, 0, 3, 1, 4, 3, 1, 4, 0, 1, 0, 3, 4, 2, 4, 1, 1,
       2, 4, 0, 2, 3, 0, 0, 2, 2, 3, 4, 0, 3, 4, 1, 3, 3, 3, 1, 4, 0, 4,
       2, 4, 3, 2, 4, 2, 4, 4, 3, 3, 1, 2, 2, 1])

In [20]:
# visualizando dados graficamente

grafico = px.scatter(x=X_random[ :, 0], y=X_random[ :, 1])
grafico.show()

In [21]:
# definindo modelo

kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

KMeans(n_clusters=5)

In [22]:
# visualizando registros em seus grupos

rotulos = kmeans_blobs.predict(X_random)
rotulos

array([4, 1, 0, 3, 2, 3, 3, 2, 4, 1, 3, 1, 3, 1, 4, 4, 1, 1, 2, 4, 4, 3,
       0, 3, 3, 4, 2, 4, 2, 1, 2, 1, 4, 3, 3, 1, 4, 4, 2, 4, 4, 0, 0, 0,
       3, 0, 4, 3, 1, 2, 2, 3, 0, 0, 2, 3, 1, 3, 2, 0, 4, 0, 2, 0, 2, 4,
       3, 4, 3, 3, 1, 2, 2, 4, 0, 3, 3, 3, 0, 2, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 4, 2, 4, 0, 4, 0, 0, 2, 0, 4, 2, 1, 1, 1, 1, 4, 4, 0, 0, 2, 2,
       4, 0, 2, 1, 4, 2, 3, 1, 0, 1, 2, 1, 0, 4, 3, 0, 3, 0, 0, 4, 2, 0,
       3, 1, 2, 4, 4, 2, 4, 0, 4, 2, 4, 2, 4, 1, 0, 4, 0, 0, 2, 1, 0, 0,
       1, 3, 2, 1, 2, 4, 2, 1, 2, 3, 0, 1, 0, 4, 0, 0, 3, 2, 1, 2, 0, 0,
       3, 3, 4, 2, 0, 0, 3, 2, 3, 4, 4, 1, 1, 3, 2, 3, 0, 1, 3, 2, 1, 0,
       1, 0, 3, 2, 3, 3, 4, 3, 2, 3, 2, 1, 1, 0, 4, 1, 2, 1, 1, 4, 0, 3,
       4, 3, 3, 1, 3, 1, 0, 2, 3, 2, 1, 0, 3, 1, 3, 0, 3, 3, 1, 2, 0, 1,
       1, 3, 4, 0, 1, 1, 3, 4, 2, 1, 4, 2, 1, 3, 2, 3, 4, 1, 0, 1, 2, 2,
       0, 1, 3, 0, 4, 1, 3, 0, 0, 4, 1, 3, 4, 4, 2, 4, 4, 4, 2, 1, 3, 1,
       0, 1, 4, 0, 1, 0, 1, 1, 4, 4, 2, 0, 0, 2])

In [24]:
centroides = kmeans_blobs.cluster_centers_
centroides

array([[-7.00389287, -8.08756341],
       [-1.99231042,  0.94147809],
       [-9.8646619 , -3.95836121],
       [-1.64707824,  4.54210493],
       [-6.21468081, -2.78778269]])

In [26]:
# visualização grafica dos agrupamentos

grafico1 = px.scatter(x= X_random[ :, 0], y= X_random[ :, 1], color=rotulos)
grafico2 = px.scatter(x= centroides[ :, 0], y= centroides[ :, 1], size=[5, 5, 5,5,5])
grafico3 = go.Figure(data= grafico1.data + grafico2.data)

grafico3.show()