In [13]:
# importando o módulo de aprendizado de máquina de Regressão Logística

import numpy as np                                     # importando o módulo para trabalhar calculos matemáticos
import pickle as pkl                                   # importando o módulo para salvar o modelo tratado em uma variavel
from sklearn.linear_model import LogisticRegression    # importando o módulo de aprendizado de máquina de Regressão Logística

In [2]:
# leitura da base de dados que ja foram tratadas e salvas

with open('./data/risc_credit.pkl', 'rb') as f:
    X_risc_credit, y_risc_credit = pkl.load(f)

In [4]:
# visualizando tamnho da base de dados

X_risc_credit.shape, y_risc_credit.shape

((14, 4), (14,))

In [5]:
# criando o modelo de regressão logística e treinamento do modelo

rl_risc_credit = LogisticRegression()
rl_risc_credit.fit(X_risc_credit, y_risc_credit)

LogisticRegression()

In [6]:
# visualizando os coeficientes do modelo

rl_risc_credit.coef_

array([[ 0.61513831, -0.34196498,  0.49067887, -0.79369827],
       [-0.72760403,  0.135437  , -0.29167359,  0.96796844],
       [ 0.11246572,  0.20652798, -0.19900528, -0.17427017]])

In [7]:
# visualizando os interceptos do modelo

rl_risc_credit.intercept_

array([ 0.55733877, -0.59215165,  0.03481289])

In [9]:
# previsão do modelo

previsoes_rl = rl_risc_credit.predict([[0, 0, 1, 2], [2, 0, 0, 0]])
previsoes_rl

array(['baixo', 'alto'], dtype=object)

In [10]:
# visualização da base de dados

X_risc_credit

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [11]:
# visualização das classes da base de dados

y_risc_credit

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [12]:
# modificação da base de dados para ter apenas 2 classes

In [14]:
# tirando a classe moderado dos registros

X_risc_credit = np.delete(X_risc_credit, [2, 7, 11], axis=0)
y_risc_credit = np.delete(y_risc_credit, [2, 7, 11], axis=0)

In [15]:
# visualização da base de dados com as classes modificadas

y_risc_credit

array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'alto', 'baixo', 'baixo',
       'alto', 'baixo', 'alto'], dtype=object)

In [16]:
# criação do modelo de regressão logística e treinamento do modelo

lr_risc_credit = LogisticRegression( random_state = 1 )
lr_risc_credit.fit( X_risc_credit, y_risc_credit )

LogisticRegression(random_state=1)

In [17]:
# visualização do intercept do modelo

lr_risc_credit.intercept_

array([-0.80828993])

In [18]:
# visualização dos coeficientes do modelo

lr_risc_credit.coef_

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

In [19]:
# previsão do modelo


previsoes_lr = rl_risc_credit.predict([[0, 0, 1, 2], [2, 0, 0, 0]])
previsoes_lr

array(['baixo', 'alto'], dtype=object)